Deployment:
  Replicas: 2
  ContainerName: api-server
  Image: heheh13/apiserver:1.1.3
  ContainerPort: 8080

Labels:
  app: api-server

Service:
  type: ClusterIP
  Port: 8080
  TargetPort: 8080

Ingress:
  Host: heheh
  Path: /
  PathType: Prefix
  PortNumber: 8080
  

